/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.poc.home.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the HomeEntry service. Represents a row in the &quot;DG_HomeEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.poc.home.model.impl.HomeEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.poc.home.model.impl.HomeEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HomeEntry
 * @generated
 */
@ProviderType
public interface HomeEntryModel
	extends BaseModel<HomeEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a home entry model instance should use the {@link HomeEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this home entry.
	 *
	 * @return the primary key of this home entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this home entry.
	 *
	 * @param primaryKey the primary key of this home entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this home entry.
	 *
	 * @return the uuid of this home entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this home entry.
	 *
	 * @param uuid the uuid of this home entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the home ID of this home entry.
	 *
	 * @return the home ID of this home entry
	 */
	public long getHomeId();

	/**
	 * Sets the home ID of this home entry.
	 *
	 * @param homeId the home ID of this home entry
	 */
	public void setHomeId(long homeId);

	/**
	 * Returns the group ID of this home entry.
	 *
	 * @return the group ID of this home entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this home entry.
	 *
	 * @param groupId the group ID of this home entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this home entry.
	 *
	 * @return the company ID of this home entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this home entry.
	 *
	 * @param companyId the company ID of this home entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this home entry.
	 *
	 * @return the user ID of this home entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this home entry.
	 *
	 * @param userId the user ID of this home entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this home entry.
	 *
	 * @return the user uuid of this home entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this home entry.
	 *
	 * @param userUuid the user uuid of this home entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this home entry.
	 *
	 * @return the user name of this home entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this home entry.
	 *
	 * @param userName the user name of this home entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this home entry.
	 *
	 * @return the create date of this home entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this home entry.
	 *
	 * @param createDate the create date of this home entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this home entry.
	 *
	 * @return the modified date of this home entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this home entry.
	 *
	 * @param modifiedDate the modified date of this home entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the address of this home entry.
	 *
	 * @return the address of this home entry
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this home entry.
	 *
	 * @param address the address of this home entry
	 */
	public void setAddress(String address);

	/**
	 * Returns the floor of this home entry.
	 *
	 * @return the floor of this home entry
	 */
	public int getFloor();

	/**
	 * Sets the floor of this home entry.
	 *
	 * @param floor the floor of this home entry
	 */
	public void setFloor(int floor);

	/**
	 * Returns the square of this home entry.
	 *
	 * @return the square of this home entry
	 */
	public float getSquare();

	/**
	 * Sets the square of this home entry.
	 *
	 * @param square the square of this home entry
	 */
	public void setSquare(float square);

	/**
	 * Returns the room of this home entry.
	 *
	 * @return the room of this home entry
	 */
	public int getRoom();

	/**
	 * Sets the room of this home entry.
	 *
	 * @param room the room of this home entry
	 */
	public void setRoom(int room);

	/**
	 * Returns the color of this home entry.
	 *
	 * @return the color of this home entry
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this home entry.
	 *
	 * @param color the color of this home entry
	 */
	public void setColor(String color);

	/**
	 * Returns the owner of this home entry.
	 *
	 * @return the owner of this home entry
	 */
	@AutoEscape
	public String getOwner();

	/**
	 * Sets the owner of this home entry.
	 *
	 * @param owner the owner of this home entry
	 */
	public void setOwner(String owner);

	@Override
	public HomeEntry cloneWithOriginalValues();

}